//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RentNow.GlobalPay {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="https://www.eazypaynigeria.com/globalpay_demo/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback postTransactionGlobalPayOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::RentNow.Properties.Settings.Default.RentNow_ng_com_globalpay_demo_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getTransactionsCompletedEventHandler getTransactionsCompleted;
        
        /// <remarks/>
        public event postTransactionGlobalPayCompletedEventHandler postTransactionGlobalPayCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.eazypaynigeria.com/globalpay_demo/getTransactions", RequestNamespace="https://www.eazypaynigeria.com/globalpay_demo/", ResponseNamespace="https://www.eazypaynigeria.com/globalpay_demo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTransactions(string merch_txnref, string channel, string merchantID, string start_date, string end_date, string uid, string pwd, string payment_status) {
            object[] results = this.Invoke("getTransactions", new object[] {
                        merch_txnref,
                        channel,
                        merchantID,
                        start_date,
                        end_date,
                        uid,
                        pwd,
                        payment_status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTransactionsAsync(string merch_txnref, string channel, string merchantID, string start_date, string end_date, string uid, string pwd, string payment_status) {
            this.getTransactionsAsync(merch_txnref, channel, merchantID, start_date, end_date, uid, pwd, payment_status, null);
        }
        
        /// <remarks/>
        public void getTransactionsAsync(string merch_txnref, string channel, string merchantID, string start_date, string end_date, string uid, string pwd, string payment_status, object userState) {
            if ((this.getTransactionsOperationCompleted == null)) {
                this.getTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransactionsOperationCompleted);
            }
            this.InvokeAsync("getTransactions", new object[] {
                        merch_txnref,
                        channel,
                        merchantID,
                        start_date,
                        end_date,
                        uid,
                        pwd,
                        payment_status}, this.getTransactionsOperationCompleted, userState);
        }
        
        private void OngetTransactionsOperationCompleted(object arg) {
            if ((this.getTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransactionsCompleted(this, new getTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.eazypaynigeria.com/globalpay_demo/postTransactionGlobalPay", RequestNamespace="https://www.eazypaynigeria.com/globalpay_demo/", ResponseNamespace="https://www.eazypaynigeria.com/globalpay_demo/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postTransactionGlobalPay(string merchantid, decimal amount, string currency, string field_details, string uid, string pwd) {
            object[] results = this.Invoke("postTransactionGlobalPay", new object[] {
                        merchantid,
                        amount,
                        currency,
                        field_details,
                        uid,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void postTransactionGlobalPayAsync(string merchantid, decimal amount, string currency, string field_details, string uid, string pwd) {
            this.postTransactionGlobalPayAsync(merchantid, amount, currency, field_details, uid, pwd, null);
        }
        
        /// <remarks/>
        public void postTransactionGlobalPayAsync(string merchantid, decimal amount, string currency, string field_details, string uid, string pwd, object userState) {
            if ((this.postTransactionGlobalPayOperationCompleted == null)) {
                this.postTransactionGlobalPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostTransactionGlobalPayOperationCompleted);
            }
            this.InvokeAsync("postTransactionGlobalPay", new object[] {
                        merchantid,
                        amount,
                        currency,
                        field_details,
                        uid,
                        pwd}, this.postTransactionGlobalPayOperationCompleted, userState);
        }
        
        private void OnpostTransactionGlobalPayOperationCompleted(object arg) {
            if ((this.postTransactionGlobalPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postTransactionGlobalPayCompleted(this, new postTransactionGlobalPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getTransactionsCompletedEventHandler(object sender, getTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void postTransactionGlobalPayCompletedEventHandler(object sender, postTransactionGlobalPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postTransactionGlobalPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postTransactionGlobalPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591