//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentNow.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.eazypaynigeria.com/globalpay_demo/", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name merch_txnref from namespace https://www.eazypaynigeria.com/globalpay_demo/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eazypaynigeria.com/globalpay_demo/getTransactions", ReplyAction="*")]
        RentNow.ServiceReference1.getTransactionsResponse getTransactions(RentNow.ServiceReference1.getTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eazypaynigeria.com/globalpay_demo/getTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<RentNow.ServiceReference1.getTransactionsResponse> getTransactionsAsync(RentNow.ServiceReference1.getTransactionsRequest request);
        
        // CODEGEN: Generating message contract since element name merchantid from namespace https://www.eazypaynigeria.com/globalpay_demo/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eazypaynigeria.com/globalpay_demo/postTransactionGlobalPay", ReplyAction="*")]
        RentNow.ServiceReference1.postTransactionGlobalPayResponse postTransactionGlobalPay(RentNow.ServiceReference1.postTransactionGlobalPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eazypaynigeria.com/globalpay_demo/postTransactionGlobalPay", ReplyAction="*")]
        System.Threading.Tasks.Task<RentNow.ServiceReference1.postTransactionGlobalPayResponse> postTransactionGlobalPayAsync(RentNow.ServiceReference1.postTransactionGlobalPayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTransactions", Namespace="https://www.eazypaynigeria.com/globalpay_demo/", Order=0)]
        public RentNow.ServiceReference1.getTransactionsRequestBody Body;
        
        public getTransactionsRequest() {
        }
        
        public getTransactionsRequest(RentNow.ServiceReference1.getTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.eazypaynigeria.com/globalpay_demo/")]
    public partial class getTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merch_txnref;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string channel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string start_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string end_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string uid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string payment_status;
        
        public getTransactionsRequestBody() {
        }
        
        public getTransactionsRequestBody(string merch_txnref, string channel, string merchantID, string start_date, string end_date, string uid, string pwd, string payment_status) {
            this.merch_txnref = merch_txnref;
            this.channel = channel;
            this.merchantID = merchantID;
            this.start_date = start_date;
            this.end_date = end_date;
            this.uid = uid;
            this.pwd = pwd;
            this.payment_status = payment_status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTransactionsResponse", Namespace="https://www.eazypaynigeria.com/globalpay_demo/", Order=0)]
        public RentNow.ServiceReference1.getTransactionsResponseBody Body;
        
        public getTransactionsResponse() {
        }
        
        public getTransactionsResponse(RentNow.ServiceReference1.getTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.eazypaynigeria.com/globalpay_demo/")]
    public partial class getTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTransactionsResult;
        
        public getTransactionsResponseBody() {
        }
        
        public getTransactionsResponseBody(string getTransactionsResult) {
            this.getTransactionsResult = getTransactionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postTransactionGlobalPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postTransactionGlobalPay", Namespace="https://www.eazypaynigeria.com/globalpay_demo/", Order=0)]
        public RentNow.ServiceReference1.postTransactionGlobalPayRequestBody Body;
        
        public postTransactionGlobalPayRequest() {
        }
        
        public postTransactionGlobalPayRequest(RentNow.ServiceReference1.postTransactionGlobalPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.eazypaynigeria.com/globalpay_demo/")]
    public partial class postTransactionGlobalPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string field_details;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pwd;
        
        public postTransactionGlobalPayRequestBody() {
        }
        
        public postTransactionGlobalPayRequestBody(string merchantid, decimal amount, string currency, string field_details, string uid, string pwd) {
            this.merchantid = merchantid;
            this.amount = amount;
            this.currency = currency;
            this.field_details = field_details;
            this.uid = uid;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postTransactionGlobalPayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postTransactionGlobalPayResponse", Namespace="https://www.eazypaynigeria.com/globalpay_demo/", Order=0)]
        public RentNow.ServiceReference1.postTransactionGlobalPayResponseBody Body;
        
        public postTransactionGlobalPayResponse() {
        }
        
        public postTransactionGlobalPayResponse(RentNow.ServiceReference1.postTransactionGlobalPayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.eazypaynigeria.com/globalpay_demo/")]
    public partial class postTransactionGlobalPayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string postTransactionGlobalPayResult;
        
        public postTransactionGlobalPayResponseBody() {
        }
        
        public postTransactionGlobalPayResponseBody(string postTransactionGlobalPayResult) {
            this.postTransactionGlobalPayResult = postTransactionGlobalPayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : RentNow.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<RentNow.ServiceReference1.ServiceSoap>, RentNow.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentNow.ServiceReference1.getTransactionsResponse RentNow.ServiceReference1.ServiceSoap.getTransactions(RentNow.ServiceReference1.getTransactionsRequest request) {
            return base.Channel.getTransactions(request);
        }
        
        public string getTransactions(string merch_txnref, string channel, string merchantID, string start_date, string end_date, string uid, string pwd, string payment_status) {
            RentNow.ServiceReference1.getTransactionsRequest inValue = new RentNow.ServiceReference1.getTransactionsRequest();
            inValue.Body = new RentNow.ServiceReference1.getTransactionsRequestBody();
            inValue.Body.merch_txnref = merch_txnref;
            inValue.Body.channel = channel;
            inValue.Body.merchantID = merchantID;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.uid = uid;
            inValue.Body.pwd = pwd;
            inValue.Body.payment_status = payment_status;
            RentNow.ServiceReference1.getTransactionsResponse retVal = ((RentNow.ServiceReference1.ServiceSoap)(this)).getTransactions(inValue);
            return retVal.Body.getTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentNow.ServiceReference1.getTransactionsResponse> RentNow.ServiceReference1.ServiceSoap.getTransactionsAsync(RentNow.ServiceReference1.getTransactionsRequest request) {
            return base.Channel.getTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentNow.ServiceReference1.getTransactionsResponse> getTransactionsAsync(string merch_txnref, string channel, string merchantID, string start_date, string end_date, string uid, string pwd, string payment_status) {
            RentNow.ServiceReference1.getTransactionsRequest inValue = new RentNow.ServiceReference1.getTransactionsRequest();
            inValue.Body = new RentNow.ServiceReference1.getTransactionsRequestBody();
            inValue.Body.merch_txnref = merch_txnref;
            inValue.Body.channel = channel;
            inValue.Body.merchantID = merchantID;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.uid = uid;
            inValue.Body.pwd = pwd;
            inValue.Body.payment_status = payment_status;
            return ((RentNow.ServiceReference1.ServiceSoap)(this)).getTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentNow.ServiceReference1.postTransactionGlobalPayResponse RentNow.ServiceReference1.ServiceSoap.postTransactionGlobalPay(RentNow.ServiceReference1.postTransactionGlobalPayRequest request) {
            return base.Channel.postTransactionGlobalPay(request);
        }
        
        public string postTransactionGlobalPay(string merchantid, decimal amount, string currency, string field_details, string uid, string pwd) {
            RentNow.ServiceReference1.postTransactionGlobalPayRequest inValue = new RentNow.ServiceReference1.postTransactionGlobalPayRequest();
            inValue.Body = new RentNow.ServiceReference1.postTransactionGlobalPayRequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.amount = amount;
            inValue.Body.currency = currency;
            inValue.Body.field_details = field_details;
            inValue.Body.uid = uid;
            inValue.Body.pwd = pwd;
            RentNow.ServiceReference1.postTransactionGlobalPayResponse retVal = ((RentNow.ServiceReference1.ServiceSoap)(this)).postTransactionGlobalPay(inValue);
            return retVal.Body.postTransactionGlobalPayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentNow.ServiceReference1.postTransactionGlobalPayResponse> RentNow.ServiceReference1.ServiceSoap.postTransactionGlobalPayAsync(RentNow.ServiceReference1.postTransactionGlobalPayRequest request) {
            return base.Channel.postTransactionGlobalPayAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentNow.ServiceReference1.postTransactionGlobalPayResponse> postTransactionGlobalPayAsync(string merchantid, decimal amount, string currency, string field_details, string uid, string pwd) {
            RentNow.ServiceReference1.postTransactionGlobalPayRequest inValue = new RentNow.ServiceReference1.postTransactionGlobalPayRequest();
            inValue.Body = new RentNow.ServiceReference1.postTransactionGlobalPayRequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.amount = amount;
            inValue.Body.currency = currency;
            inValue.Body.field_details = field_details;
            inValue.Body.uid = uid;
            inValue.Body.pwd = pwd;
            return ((RentNow.ServiceReference1.ServiceSoap)(this)).postTransactionGlobalPayAsync(inValue);
        }
    }
}
